# Numpy :
## NumPy lets you store and process numerical data (like lists of numbers, tables, and matrices) in a fast, mathematical way. 📊
## ***i.e., used for creating arrays and matrices***

In [1]:
!pip install numpy

In [3]:
import numpy as np

## Create arrays using numpy
## 1D array
a1 = np.array([1,2,3,4,5])
print(a1)
print(type(a1))
print(a1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [ ]:
a2 = np.array([1,2,3,4,5])
a2.reshape(1, 5) # 1 row and 5 columns

array([[1, 2, 3, 4, 5]])

In [ ]:
## 2D array
a2 = np.array([[1,2,3,4,5], [2,3,4,5,6]])
print(a2)
a2.shape

[[1 2 3 4 5]
 [2 3 4 5 6]]


(2, 5)

In [12]:
np.arange(0, 10, 2).reshape(5, 1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [ ]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
## identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
## Attributes of Numpy Array
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Array:\n", arr)
print("Shape:", arr.shape) 
print("Number of dimensions:", arr.ndim)  
print("Size (number of elements):", arr.size) 
print("Data type:", arr.dtype)  
print("Item size (in bytes):", arr.itemsize) 

Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimensions: 2
Size (number of elements): 6
Data type: int64
Item size (in bytes): 8


In [18]:
## Numpy Vectorised Operations
a1 = np.array([1,2,3,4,5])
a2 = np.array([10, 20, 30, 40, 50])

## Element wise addition
print('Addition :', a1+a2)

## Element wise substraction
print('Substraction :', a1-a2) 

## Element wise multipication
print('Multiplication :', a1*a2)

## Element wise division
print('Division :', a1/a2)

Addition : [11 22 33 44 55]
Substraction : [ -9 -18 -27 -36 -45]
Multiplication : [ 10  40  90 160 250]
Division : [0.1 0.1 0.1 0.1 0.1]


In [19]:
## Universal function
a = np.array([2,3,4,5,6])

## Square root
print(np.sqrt(a))

## Exponential 
print(np.exp(a))

## Sine
print(np.sin(a))

## natural log
print(np.log(a))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [4]:
## Array slicing and indexing
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print('Array :\n', a)

Array :
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [10]:
print(a[0][0])
print(a[0:2, 2:])

1
[[3 4]
 [7 8]]


In [ ]:
a[1:,2:] # '1:' for row; '2:' for col

array([[ 7,  8],
       [11, 12]])

In [45]:
## Array for 6 7 10 11
print(a[1:, 1:3])

[[ 6  7]
 [10 11]]


In [49]:
## Modify array elements
a[0,0] = 100
print(a)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [50]:
a[1:] = 100
print(a)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [51]:
## Normilization
## to have a mean of 0 and a standard deviation of 1
data = np.array([1, 2, 3, 4, 5])

# Calculate the mean and standard deviation
mean = np.mean(data)
std_dev = np.std(data)

# Normalize the data
normalized_data = (data - mean) / std_dev
print("Normalized data:", normalized_data)

Normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [52]:
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Mean
mean = np.mean(data)
print("Mean:", mean)

# Median
median = np.median(data)
print("Median:", median)

# Standard deviation
std_dev = np.std(data)
print("Standard Deviation:", std_dev)

# Variance
variance = np.var(data)
print("Variance:", variance)

Mean: 5.5
Median: 5.5
Standard Deviation: 2.8722813232690143
Variance: 8.25


In [57]:
## logical operations
data = np.array([1,2,3,4,5,6,7,8,9,10])

data[(data>=5) & (data<=8)]

array([5, 6, 7, 8])