### Assignment 1: Array Creation and Manipulation

In [2]:
# 1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. 
import numpy as np
a1 = np.random.randint(1, 21, size=(5,5))
print(f'Original array 1:\n{a1}\n')

## Replace all the elements in third column with 1.
a1[:, 2] = 1
print(f'Modified array 1:\n{a1}\n\n')

Original array 1:
[[ 9  4 12 11  7]
 [ 9  7  8 16 19]
 [17  4 16  5  7]
 [ 9  6 20  6 17]
 [ 7  8  9 11 18]]

Modified array 1:
[[ 9  4  1 11  7]
 [ 9  7  1 16 19]
 [17  4  1  5  7]
 [ 9  6  1  6 17]
 [ 7  8  1 11 18]]




In [10]:
# 2. Create a NumPy array of shape (4, 4) with values from 1 to 16.
a2 = np.arange(1,17).reshape(4,4)
print(f'Original array 2:\n{a2}\n')

## Replace the diagonal elements with 0.
np.fill_diagonal(a2, 0)
print(f'Modified array 2:\n{a2}')

Original array 2:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Modified array 2:
[[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]


### Assignment 2: Array Indexing and Slicing

In [11]:
# 1. Create a NumPy array of shape (6, 6) with values from 1 to 36.
a1 = np.arange(1,37).reshape(6,6)
print(f'Original Array 1:\n{a1}\n')

## Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
sub_a1 = a1[2:5, 1:4]
print(f'Modified Array 1:\n{sub_a1}\n\n')

Original Array 1:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]

Modified Array 1:
[[14 15 16]
 [20 21 22]
 [26 27 28]]




In [12]:
# 2. Create a NumPy array of shape (5, 5) with random integers.
a2 = np.random.randint(1, 21, size=(5,5))
print(f'Original Array 2:\n{a2}\n')

## Extract the elements on the border.
border_a2 = np.concatenate((a2[0,:], a2[-1, :], a2[1:-1, 0], a2[1:-1, -1]))
print(f'Border Elements:\n{border_a2}')

Original Array 2:
[[11  5 14 19  6]
 [18 17 20 10 19]
 [15  8  9 19 13]
 [ 8  6 14 16  7]
 [ 7  7 19 14 16]]

Border Elements:
[11  5 14 19  6  7  7 19 14 16 18 15  8 19 13  7]


### Assignment 3: Array Operations

In [13]:
# 1. Create two NumPy arrays of shape (3, 4) filled with random integers.
a1 = np.random.randint(1,11,size=(3,4))
a2 = np.random.randint(1,11,size=(3,4))
print(f'Original Array 1:\n{a1}')
print(f'\nOriginal Array 2:\n{a2}\n')

## Perform element-wise addition, subtraction, multiplication, and division.
print(f'Addition:\n{a1+a2}\n')
print(f'Subtraction:\n{a1-a2}\n')
print(f'Multiplication:\n{a1*a2}\n')
print(f'Division:\n{a1/a2}')

Original Array 1:
[[7 7 9 8]
 [1 4 9 9]
 [1 7 5 3]]

Original Array 2:
[[ 4  3  6  5]
 [ 7  5 10  4]
 [ 5  1  9  9]]

Addition:
[[11 10 15 13]
 [ 8  9 19 13]
 [ 6  8 14 12]]

Subtraction:
[[ 3  4  3  3]
 [-6 -1 -1  5]
 [-4  6 -4 -6]]

Multiplication:
[[28 21 54 40]
 [ 7 20 90 36]
 [ 5  7 45 27]]

Division:
[[1.75       2.33333333 1.5        1.6       ]
 [0.14285714 0.8        0.9        2.25      ]
 [0.2        7.         0.55555556 0.33333333]]


In [14]:
# 2. Create a NumPy array of shape (4, 4) with values from 1 to 16.
a = np.arange(1,17).reshape(4,4)
print(f'Array:\n{a}')

## Compute the row-wise and column-wise sum.
row_sum = np.sum(a, axis=1)
col_sum = np.sum(a, axis=0)
print(f'Row Sum:{row_sum}\nColumn Sum:{col_sum}')

Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Row Sum:[10 26 42 58]
Column Sum:[28 32 36 40]


### Assignment 4: Statistical Operations

In [15]:
# 1. Create a NumPy array of shape (5, 5) filled with random integers.
a = np.random.randint(1, 21, size=(5,5))
print(f'Original Array:\n{a}')

## Compute the mean, median, standard deviation, and variance of the array.
print(f'\nMean : {np.mean(a)}')
print(f'Median : {np.median(a)}')
print(f'Standard Deviation : {np.std(a)}')
print(f'Variance : {np.var(a)}')

Original Array:
[[ 7 17 20 12  2]
 [ 8 11  4 19  4]
 [15  2  8  5  4]
 [17  4  3 13 20]
 [10  6  1  5  1]]

Mean : 8.72
Median : 7.0
Standard Deviation : 6.141791269654155
Variance : 37.721599999999995


In [16]:
# 2. Create a NumPy array of shape (3, 3) with values from 1 to 9.
a = np.arange(1,10).reshape(3,3)
print('Array :\n',a)

## Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).
normalised_a = (a - np.mean(a))/np.std(a)
print('\nNormalized Array :\n', normalised_a)

Array :
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Normalized Array :
 [[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]


### Assignment 5: Broadcasting

In [17]:
# 1. Create a NumPy array of shape (3, 3) filled with random integers.
a = np.random.randint(1,11, size=(3,3))
print(f'Original Array:\n{a}\n')

## Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
r_a = np.random.randint(1,11, size=(3,))
print(f'1D Array :\n{r_a}\n')
print(f'Resulting Array :\n{a+r_a}')

Original Array:
[[9 4 4]
 [2 6 6]
 [9 3 6]]

1D Array :
[ 6 10 10]

Resulting Array :
[[15 14 14]
 [ 8 16 16]
 [15 13 16]]


In [18]:
# 2. Create a NumPy array of shape (4, 4) filled with random integers.
a = np.random.randint(1,11, size=(4,4))
print(f'Array :\n{a}\n')

## Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.
c_a = np.random.randint(1,11, size=(4,))
print(f'1D Array :\n{c_a}\n')
print(f'Resulting Array :\n{a - c_a[:, np.newaxis]}')

Array :
[[ 3  5 10  9]
 [ 5  6  3 10]
 [ 2  9  3  6]
 [ 6  7  7  4]]

1D Array :
[3 7 6 5]

Resulting Array :
[[ 0  2  7  6]
 [-2 -1 -4  3]
 [-4  3 -3  0]
 [ 1  2  2 -1]]


### Assignment 6: Linear Algebra

In [19]:
# 1. Create a NumPy array of shape (3, 3) representing a matrix.
a = np.random.randint(1, 10, size=(3,3))
print(f'Matrix :\n{a}')

## Compute its determinant, inverse, and eigenvalues.
determinant = np.linalg.det(a)
inverse = np.linalg.inv(a)
eigen = np.linalg.eigvals(a)

print(f'\nDeterminant : {determinant}\n')
print(f'Inverse :\n {inverse}\n')
print(f'Eigen Values : {eigen}')

Matrix :
[[3 3 1]
 [8 7 7]
 [8 5 4]]

Determinant : 34.99999999999999

Inverse :
 [[-0.2        -0.2         0.4       ]
 [ 0.68571429  0.11428571 -0.37142857]
 [-0.45714286  0.25714286 -0.08571429]]

Eigen Values : [14.5763546+0.j         -0.2881773+1.52253174j -0.2881773-1.52253174j]


In [20]:
# 2. Create two NumPy arrays of shape (2, 3) and (3, 2).
matrix1 = np.random.randint(1, 11, size=(2,3))
matrix2 = np.random.randint(1, 11, size=(3,2))
print(f'Matrix 1 :\n{matrix1}\n')
print(f'Matrix 2 :\n{matrix2}\n')
 
## Perform matrix multiplication on these arrays.
print(f'Matrix Multiplication :\n{np.dot(matrix1, matrix2)}')

Matrix 1 :
[[ 1  7 10]
 [ 5  7  4]]

Matrix 2 :
[[1 1]
 [3 3]
 [4 4]]

Matrix Multiplication :
[[62 62]
 [42 42]]


### Assignment 7: Advanced Array Manipulation

In [21]:
# 1. Create a NumPy array of shape (3, 3) with values from 1 to 9.
a = np.arange(1,10).reshape((3,3))
print('Array :\n', a)

# Reshape the array to shape (1, 9) and then to shape (9, 1).
reshaped_a1 = a.reshape(1,9)
reshaped_a2 = a.reshape(9,1)
print(f'\nReshaped array (1,9):\n{reshaped_a1}')
print(f'\nReshaped array (9,1):\n{reshaped_a2}')

Array :
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Reshaped array (1,9):
[[1 2 3 4 5 6 7 8 9]]

Reshaped array (9,1):
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [22]:
# 2. Create a NumPy array of shape (5, 5) filled with random integers.
a = np.random.randint(1, 21, size=(5,5))
print(f'Array :\n{a}\n')

## Flatten the array and then reshape it back to (5, 5).
flattened_a = a.flatten()
print(f'Flattened array :\n{flattened_a}')
print(f'Reshaped array:\n{flattened_a.reshape((5,5))}')

Array :
[[ 1 18  2 18 11]
 [ 8  5  4  9  4]
 [ 3  7 17 19 12]
 [20 11 19  3  4]
 [14 20 11  7  2]]

Flattened array :
[ 1 18  2 18 11  8  5  4  9  4  3  7 17 19 12 20 11 19  3  4 14 20 11  7
  2]
Reshaped array:
[[ 1 18  2 18 11]
 [ 8  5  4  9  4]
 [ 3  7 17 19 12]
 [20 11 19  3  4]
 [14 20 11  7  2]]


### Assignment 8: Fancy Indexing and Boolean Indexing

In [23]:
# 1. Create a NumPy array of shape (5, 5) filled with random integers.
a = np.random.randint(1,11,size=(5,5))
print(f'Array :\n{a}')

## Use fancy indexing to extract the elements at the corners of the array.
corners = a[[0,0,-1,-1], [0,-1,0,-1]]
print(f'\nCorners : {corners}')

Array :
[[ 3  9  1  8  9]
 [ 5  5  2  2  3]
 [ 8  1 10  1  4]
 [ 3  8  8  2  3]
 [ 6  1  8  9  9]]

Corners : [3 9 6 9]


In [24]:
# 2. Create a NumPy array of shape (4, 4) filled with random integers.
a = np.random.randint(1,21, size=(4,4))
print(f'Array :\n{a}')

## Use boolean indexing to set all elements greater than 10 to 10.
a[a>10] = 10
print(f'\nModified array:\n{a}')

Array :
[[ 7 18  6  4]
 [19 19 16  8]
 [ 3  9  1 17]
 [ 5 19 20 16]]

Modified array:
[[ 7 10  6  4]
 [10 10 10  8]
 [ 3  9  1 10]
 [ 5 10 10 10]]


### Assignment 9: Structured Arrays

In [ ]:
# 1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float).
data_type = [('name', 'U10'), ('age', 'i4'), ('weight', 'f4')]
data = np.array([('Alice', 25, 55.5), ('Bob', 30, 85.3), ('Charlie', 20, 65.2)], dtype=data_type)
print(f'Array :  {data}')

## Add some data and sort the array by age.
sorted_data = np.sort(data, order='age')
print(f'Array sorted by age:  {sorted_data}')

Array :  [('Alice', 25, 55.5) ('Bob', 30, 85.3) ('Charlie', 20, 65.2)]
Array sorted by age:  [('Charlie', 20, 65.2) ('Alice', 25, 55.5) ('Bob', 30, 85.3)]


In [27]:
# 2. Create a structured array with fields 'x' and 'y' (both integers). 
data_type = [('x', 'i4'), ('y', 'i4')]
data = np.array([(1, 2), (3, 4), (5, 6)], dtype=data_type)
print(f'Array : {data}')

## Add some data and compute the Euclidean distance between each pair of points.
distances = np.sqrt((data['x'][:, np.newaxis]-data['x'])**2 - (data['y'][:, np.newaxis]-data['y']**2))
print(f'Euclidean Distances :\n{distances}')

Array : [(1, 2) (3, 4) (5, 6)]
Euclidean Distances :
[[1.41421356 4.24264069 7.07106781]
 [2.         3.46410162 6.        ]
 [3.74165739 3.74165739 5.47722558]]


### Assignment 10: Masked Arrays

In [3]:
# 1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10.
import numpy.ma as ma
a = np.random.randint(1,21, size=(4,4))
masked_a = ma.masked_greater(a, 10)
print(f'Array :\n{a}')
print(f'Masked array :\n{masked_a}')

## Compute the sum of the unmasked elements.
print(f'\nSum of masked array : {masked_a.sum()}')

Array :
[[ 1  3 20  3]
 [11 19 19 10]
 [ 9  1 13  1]
 [ 5 13  7 15]]
Masked array :
[[1 3 -- 3]
 [-- -- -- 10]
 [9 1 -- 1]
 [5 -- 7 --]]

Sum of masked array : 40


In [7]:
# 2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements.
a = np.random.randint(1,21,size=(3,3))
masked_a = ma.masked_array(a, mask=np.eye(3, dtype=bool))
print(f'Array :\n{a}\n')
print(f'Diagonally masked array :\n{masked_a}\n')

## Replace the masked elements with the mean of the unmasked elements.
print(f'Modified masked array :\n{masked_a.filled(masked_a.mean())}')

Array :
[[ 2 20  4]
 [17 20  3]
 [20  5  8]]

Diagonally masked array :
[[-- 20 4]
 [17 -- 3]
 [20 5 --]]

Modified masked array :
[[11 20  4]
 [17 11  3]
 [20  5 11]]
